version: "2"

run:
  timeout: 5m
  modules-download-mode: readonly

linters:
  default: standard
  enable:
    - bodyclose
    - dogsled
    - errorlint
    - goconst
    - gocritic
    - gocyclo
    - gosec
    - misspell
    - nakedret
    - prealloc
    - predeclared
    - unconvert
    - unparam
    - whitespace

  settings:
    gocyclo:
      min-complexity: 20

    goconst:
      min-len: 3
      min-occurrences: 3

    misspell:
      locale: US

    gocritic:
      enabled-tags:
        - diagnostic
        - performance
      disabled-checks:
        - hugeParam

  exclusions:
    presets:
      - comments
      - std-error-handling
    rules:
      - path: _test\.go
        linters:
          - dupl
          - goconst
          - gosec
          - noctx
          - errcheck
          - gocritic
          - unparam
          - gocyclo
          - misspell
          - errorlint

      - path: examples/
        linters:
          - errcheck
          - gosec
          - gocritic
          - errorlint

      - path: e2e/
        linters:
          - errcheck
          - errorlint

formatters:
  enable:
    - gofmt
    - goimports
  settings:
    goimports:
      local-prefixes:
        - github.com/felixgeelhaar/mcp-go

issues:
  max-issues-per-linter: 0
  max-same-issues: 0
